### ISSUE TITLE
Rename Porter to PorterLB

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/porterlb#189]
A couple of reasons from my consideration:

1. There is a CNCF sandbox project [Porter](https://porter.sh) already
2. The domain name is `porterlb.io`
3. LB means Load Balancer, it might be easier to understand and memorize the project feature.

If you agree to change Porter to PorterLB, please comment on this issue and make the relevant changes accordingly.

**Comment by Patrick-LuoYu** [comment]
Agree. PorterLB sounds better to me.

**Comment by FeynmanZhou** [comment]
So far, most of the project maintainers have agreed with this proposal. Can we start to update the project name including the Github repository and website?

**Comment by duanjiong** [comment]
Of course you can, you may need someone with permission to rename the repository, and then I'll change the name of the imported package in the code later

**Comment by FeynmanZhou** [comment]
> Of course you can, you may need someone with permission to rename the repository, and then I'll change the name of the imported package in the code later

Ok, I got it.

**Comment by FeynmanZhou** [comment]
The repository and project name has been renamed. Resolved and closed.
